server:
  port: 8081

spring:
    datasource:
      url: jdbc:postgresql://localhost:54320/eternity?currentSchema=student
      username: postgres
      password: eternity123
      jpa:
        hibernate: ddl-auto=create-drop
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.PostgreSQLDialect
            format_sql: true